תרגיל 1: יצירת מערך ובדיקת תכונותיה

תיאור: צרי מערך של 10 מספרים שלמים באקראי בין 1 ל-50. בדקי את גודל המערך, סוג הנתונים ומספר הממדים שלו.

In [22]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [23]:
import numpy as np

In [24]:
random_array = np.random.randint(1,50,size = (10))
print(random_array)
print(random_array.dtype)



[12 12 43 49 12 19 25 37 38  6]
int32


In [25]:
np.ndim(random_array)

1

In [26]:
random_array.size

10

תרגיל 2: יצירת מערך דו-ממדי

תיאור: צרי מערך דו-ממדי עם 2 שורות ו-5 עמודות של מספרים אקראיים בין 10 ל-100. בדקי את הצורה של המערך.

In [28]:
try_zeros = np.random.randint(5 ,size=(2, 5))
try_zeros

array([[0, 1, 0, 0, 1],
       [2, 1, 2, 3, 0]])

צרי מערך באורך 10 של מספרים שלמים רנדומליים בין 1 ל-50 וחשבי את הממוצע של המספרים

In [29]:
myArray = np.random.randint(1,50,size=(10))
myArray

array([ 5, 42,  4,  9, 40,  8, 20, 26,  1, 19])

צרי שני מערכים דו מימדיים בגודל 3, חברי אותם, ובדקי מה הממוצע של התוצאה

In [31]:
a = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [32]:
b = np.array([[8, 9 ,10], [11, 12, 13], [14, 15, 16]])
b

array([[ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [33]:
connected = a+b
connected


array([[ 9, 11, 13],
       [15, 17, 19],
       [19, 21, 23]])

In [34]:
avg = np.mean(connected)
avg

16.333333333333332

רי מערך של 20 מספרים שלמים רנדומליים בין 1 ל-100. מצאי את כל המספרים שגדולים מ-50 במערך זה

In [35]:
hh = np.random.randint(1,100,size=(20))
hh


array([11, 59, 42, 79, 60, 33, 45, 17, 72, 31, 76, 45, 65, 47, 11, 66, 33,
       65, 30, 81])

In [37]:
condition = hh>50
big = hh[condition]
big

array([59, 79, 60, 72, 76, 65, 66, 65, 81])

רי מערך של מספרים מ-1 עד 10. ערבבי את המערך ולאחר מכן בחרי באופן אקראי אלמנטים ממנו

In [39]:
arr = ([1,2,3,4,5,6,7,8,9,10])
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [44]:
np.random.shuffle(arr)
arr

[1, 10, 7, 6, 5, 9, 3, 4, 8, 2]

In [48]:
cond = arr>0
and = arr[cond]
and

SyntaxError: invalid syntax (1575899030.py, line 2)